// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"go-venice/configs"
	"go-venice/internal/adapter/nodes"
	"go-venice/internal/api/router"
	"go-venice/internal/api/service"
)

// Injectors from wire.go:

func InitializeRouter() *gin.Engine {
	envConfig := configs.Load()
	evm := nodes.NewEvm(envConfig)
	nodeService := service.NewNodeService(envConfig, evm)
	routerConfig := router.RouterConfig{
		NodeService: nodeService,
	}
	engine := router.NewRouter(routerConfig)
	return engine
}
